### ISSUE TITLE
Not valid pattern:  ('SKIP',     r'[ \r\n\t]+|//.*?\n'),

### ISSUE THREAD

**Issue by malneni** [eerimoq/textparser#1]
When I test "SKIP" pattern https://regex101.com/ it shows error for  //
 
[ \r\n\t]+|//.*?\n

gm
All the errors detected are listed below, from left to right, as they appear in the pattern.
/ An unescaped delimiter must be escaped with a backslash (\)
/ An unescaped delimiter must be escaped with a backslash (\)

**Comment by eerimoq** [comment]
The Python regex module is not that picky it seems. Just a `/` works just fine in my tests.
