### ISSUE TITLE
IndexError when using ZeroOrMore(Any()) at end of grammar

### ISSUE THREAD

**Issue by erzoe** [eerimoq/textparser#2]
I'm trying to parse a file consisting of several groups but I only care about one of those groups. For example:
```
some_group {
	foo bar; foo bar;
};

interesting_group {
	a = 1;
	b = 2;
};

another_group {
	foo bar
};
```

So I'm skipping all tokens before the interesting group with `AnyUntil('interesting_group')` (which works as expected) and I'm trying to skip all tokens after the group with `ZeroOrMore(Any())` which raises an IndexError regardless of whether there are following tokens or not:
```
Traceback (most recent call last):
  File "test.py", line 44, in <module>
    tree = Parser().parse(text, token_tree=False)
  File "venv/lib/python3.9/site-packages/textparser.py", line 884, in parse
    return Grammar(self.grammar()).parse(tokens, token_tree)
  File "venv/lib/python3.9/site-packages/textparser.py", line 676, in parse
    parsed = self._root.match(tokens)
  File "venv/lib/python3.9/site-packages/textparser.py", line 252, in match
    mo = pattern.match(tokens)
  File "venv/lib/python3.9/site-packages/textparser.py", line 355, in match
    mo = self._pattern.match(tokens)
  File "venv/lib/python3.9/site-packages/textparser.py", line 529, in match
    return tokens.get_value()
  File "venv/lib/python3.9/site-packages/textparser.py", line 99, in get_value
    return self._tokens[pos].value
IndexError: list index out of range
```

test.py
```python
import textparser

class Parser(textparser.Parser):

	def keywords(self):
		return ['interesting_group']

	def token_specs(self):
		return [
			('SKIP',        r'[ \r\n\t]+'),
			('WORD',        r'[A-Za-z0-9_]+'),
			('SEMICOLON',   ';', r';'),
			('BRACE_OPEN',  '{', r'\{'),
			('BRACE_CLOSE', '}', r'\}'),
			('EQUAL',       '=', r'='),
		]

	def grammar(self):
		interesting_group = textparser.Sequence('interesting_group', '{',
			textparser.ZeroOrMore(textparser.Sequence('WORD', '=', 'WORD', ';')),
		'}', ';')
		return textparser.Sequence(textparser.AnyUntil('interesting_group'), interesting_group, textparser.ZeroOrMore(textparser.Any()))


text = '''
some_group {
	foo bar; foo bar;
};

interesting_group {
	a = 1;
	b = 2;
};

another_group {
	foo bar
};
'''

if __name__ == '__main__':
	from pprint import pprint
	tree = Parser().parse(text, token_tree=False)
	pprint(tree)
```

When I remove `textparser.ZeroOrMore(textparser.Any())` from the Sequence and the lines following the interesting group in text it works.

I am using Python 3.9 and textparser version 0.23.0.

**Comment by erzoe** [comment]
I have found a work around: Adding a token_spec `('EOF', r'$')` and replacing `textparser.ZeroOrMore(textparser.Any())` by `textparser.AnyUntil('EOF'), 'EOF'` works.

**Comment by eerimoq** [comment]
There is also the special token `__EOF__` which is automatically appended to the list of tokens. So `AnyUntil('__EOF__')` also works.

I changed `Any()`  to give a mismatch when matching this special end of file token. With that change your original code works. The fix will be released soon. Just have to update the repo to use github actions.

**Comment by eerimoq** [comment]
The fix is available on PyPI. textparser version 0.24.0.

**Comment by erzoe** [comment]
awesome, thank you very much
